import clsx from 'clsx'
import type { Metadata } from 'next'
import { Open_Sans, Rubik } from 'next/font/google'
import { PropsWithChildren } from 'react'

import { Footer, Sidebar } from '@/components/ui'

import { ReactQueryProvider, ReduxToolkitProvider } from '@/providers'

import './globals.css'

// const nunitoSans = Nunito_Sans({
// 	subsets: ['latin'],
// 	weight: ['200', '400', '500', '600'],
// 	style: ['normal'],
// 	display: 'swap'
// })

const OpenSans = Open_Sans({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	style: ['normal'],
	display: 'swap'
})

const rubik = Rubik({ subsets: ['latin'], weight: ['300', '400', '500'], style: ['normal'], display: 'swap' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<ReactQueryProvider>
				<ReduxToolkitProvider>
					<body className={clsx(rubik.className, OpenSans.className)}>
						<Sidebar />
						<main className='ml-5'>{children}</main>
						<Footer />
					</body>
				</ReduxToolkitProvider>
			</ReactQueryProvider>
		</html>
	)
}
