import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'

import { ReactQueryProvider } from '@/providers'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<ReactQueryProvider>
				<body className={inter.className}>{children}</body>
			</ReactQueryProvider>
		</html>
	)
}
